services:
  db:
    image: postgres:12.7
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wordbank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  load_data:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["python", "load_data.py"]

volumes:
  postgres_data:
